dist: bionic
language: ruby
rvm: 2.7
gemfile:
  - Gemfile
cache:
  directories:
  - vendor/bundle
services:
  - postgresql
  - mysql
  - elasticsearch
addons:
  postgresql: 10
script: bundle exec appraisal "rake test || true"
before_script:
  - mysqladmin create ultimate_test
  - createdb ultimate_test
  - node test/server.js &>/dev/null &
  - bundle exec appraisal install
notifications:
  email:
    on_success: never
    on_failure: change
