dist: xenial
language: ruby
rvm: 2.5.3
gemfile:
  - Gemfile
services:
  - postgresql
  - mysql
script: bundle exec rake test
before_script:
  - mysql -e 'CREATE DATABASE ultimate_test;'
  - psql -c 'CREATE DATABASE ultimate_test;' -U postgres
  - node test/server.js &>/dev/null &
env:
  - TRAVIS=t
notifications:
  email:
    on_success: never
    on_failure: change
